### ISSUE TITLE
Error setting up entry user@mail.com for mazda

### ISSUE THREAD

**Issue by pr0fetul** [bdr99/pymazda#26]
Since yesterday, it seems that the component cannot connect anymore. In logs this is the entry:
```
Logger: homeassistant.config_entries
Source: components/mazda/__init__.py:68
First occurred: August 8, 2022 at 8:10:41 AM (1 occurrences)
Last logged: August 8, 2022 at 8:10:41 AM

Error setting up entry user@mail.com for mazda
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1154, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 880, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 860, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/mazda/__init__.py", line 68, in async_setup_entry
    await mazda_client.validate_credentials()
  File "/usr/local/lib/python3.10/site-packages/pymazda/client.py", line 21, in validate_credentials
    await self.controller.login()
  File "/usr/local/lib/python3.10/site-packages/pymazda/controller.py", line 11, in login
    await self.connection.login()
  File "/usr/local/lib/python3.10/site-packages/pymazda/connection.py", line 281, in login
    encryption_key_response = await self._session.request(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host rz97suam.mazda.com:443 ssl:<ssl.SSLContext object at 0x7fa290fdcfc0> [Try again]
```

Can you take a look at it?
Home Assistant 2022.8.2
Supervisor 2022.07.0
Operating System 8.4
Frontend 20220802.0 - latest

**Comment by bdr99** [comment]
Hi @pr0fetul, I just checked and the integration is working on my side. The logs show that the DNS lookup failed, so I think this might have been just been a temporary network issue on your side. Are you still getting this error in your logs? If so, could you please try restarting your host system to see if the error persists?

**Comment by pr0fetul** [comment]
Yea, it seems you were right - I just restarted HA and it resumed working without errors - very strange (might be tied with the fact that I upgraded the FW of the router a few days ago) but other than that, there were no changes. 

Thank you so much for the fast reply. We can close the issue.

**Comment by bdr99** [comment]
Thanks for confirming!
