### ISSUE TITLE
Error: Request failed: An update to Mazda app is required to continue (March 2023)

### ISSUE THREAD

**Issue by hogantg** [bdr99/pymazda#28]
Hi @bdr99 - I think the Mazda App has updated and broken the API. Below is my log output:

```Logger: homeassistant.components.mazda
Source: components/mazda/__init__.py:54 
Integration: Mazda Connected Services ([documentation](https://www.home-assistant.io/integrations/mazda), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+mazda%22)) 
First occurred: 12:00:41 PM (10 occurrences) 
Last logged: 12:05:28 PM

Unknown error occurred during Mazda update request: Request failed: An update to Mazda app is required to continue
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mazda/__init__.py", line 151, in async_update_data
    vehicles = await with_timeout(mazda_client.get_vehicles())
  File "/usr/src/homeassistant/homeassistant/components/mazda/__init__.py", line 54, in with_timeout
    return await task
  File "/usr/local/lib/python3.10/site-packages/pymazda/client.py", line 27, in get_vehicles
    vec_base_infos_response = await self.controller.get_vec_base_infos()
  File "/usr/local/lib/python3.10/site-packages/pymazda/controller.py", line 21, in get_vec_base_infos
    return await self.connection.api_request("POST", "remoteServices/getVecBaseInfos/v4", body_dict={"internaluserid": "__INTERNAL_ID__"}, needs_keys=True, needs_auth=True)
  File "/usr/local/lib/python3.10/site-packages/pymazda/connection.py", line 162, in api_request
    return await self.__api_request_retry(method, uri, query_dict, body_dict, needs_keys, needs_auth, num_retries=0)
  File "/usr/local/lib/python3.10/site-packages/pymazda/connection.py", line 177, in __api_request_retry
    return await self.__send_api_request(method, uri, query_dict, body_dict, needs_keys, needs_auth)
  File "/usr/local/lib/python3.10/site-packages/pymazda/connection.py", line 251, in __send_api_request
    raise MazdaException("Request failed: " + response_json["error"])
pymazda.exceptions.MazdaException: Request failed: An update to Mazda app is required to continue

**Comment by bdr99** [comment]
Hi, which version of HA are you using?

**Comment by hogantg** [comment]
> Hi, which version of HA are you using?

Apologies - 2023.2.2

**Comment by bdr99** [comment]
This problem was fixed in 2023.3.3. Updating to 2023.3.3 or later should fix it.

**Comment by hogantg** [comment]
Welp - I am dumb! Sorry about that. Will update now and close the issue. Thanks for your help.

**Comment by bdr99** [comment]
No problem!
